### ISSUE TITLE
Photo-frames directory is not valid.

### ISSUE THREAD

**Issue by Deadterm1nator** [TissuePowder/YAFOT-Facebook#2]
Hi, when i put the code to upload the frames it keeps telling that the photo-frames directory is not valid. I tried a lot of things and it keeps sending me that error, what should i do?

**Comment by TissuePowder** [comment]
Do not close the issue before confirming if you solved the problem. You need to pass a valid directory with the --pdir option. If you haven't solved it yet, can you show me your full command that you ran on your console? Just the part without the token.

**Comment by Deadterm1nator** [comment]
I just needed to drag the file into the console (pdir)

**Comment by seaque** [comment]
Provide full directory. Like C:/Users/user/Documents etc. And put it in double quotes.
